graph: cro
loading_config:
  data_source:
    scheme: file  # file, oss, s3, hdfs; only file is supported now
    #location: /home/graphscope/gs_interactive_default_graph/
    location: /crodata/data
  import_option: init # append, overwrite, only init is supported now
  format:
    type: csv
    metadata:
      delimiter: ','
      batch_reader: false
      batch_size: 16MB
      quoting: true
      quote_char: '"'
      double_quote: true
vertex_mappings:
  - type_name: medium  # must align with the schema
    inputs:
      - medium.csv
    column_mappings:
      - column:
          index: 0    # can be omitted if the index is the same as the property index
          name: medium_id  # can be omitted if the name is not known
        property: id
      - column:
          index: 1
          name: medium_type
        property: type
      - column:
          index: 2
          name: medium_weight
        property: weight
  - type_name: center
    inputs:
      - real_center.csv
    column_mappings:
      - column:
          index: 0
          name: centerid
        property: id
edge_mappings:
  - type_triplet:
      edge: connect
      source_vertex:  center
      destination_vertex:  medium
    inputs:
      - center_medium.csv
    source_vertex_mappings:
      - column:
          index: 0
          name: id
        property: id
    destination_vertex_mappings:
      - column:
          index: 1
          name: id
        property: id
    column_mappings:
      - column:
          index: 2
          name: medium_weight
        property: weight