name: GraphScope Flex CI

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'flex/**'
      - '.github/workflows/flex.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'flex/**'
      - '.github/workflows/flex.yml'

concurrency:
  group: ${{ github.repository }}-${{ github.event.number || github.head_ref || github.sha }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  test-hqps-engine:
    runs-on: ubuntu-20.04
    if: ${{ github.repository == 'alibaba/GraphScope' }}
    container:
      image: registry.cn-hongkong.aliyuncs.com/graphscope/hqps-server-base:latest
    steps:
    - uses: actions/checkout@v3

    - name: Build
      run: |
        cd flex
        mkdir build && cd build
        cmake .. && make -j3

    - name: Run High QPS Engine test
      env:
        GS_TEST_DIR: ${{ github.workspace }}/gstest
      run: |
        # download dataset
        git clone -b master --single-branch --depth=1 https://github.com/GraphScope/gstest.git ${GS_TEST_DIR}
        
        flex_test_dir=${GS_TEST_DIR}/flex
        # preprocess bulk_load.yaml to use gstest_dir
        sed -i "s|workspaces/gstest|$GS_TEST_DIR|" ${flex_test_dir}/ldbc-sf01-long-date/audit_bulk_load.yaml

        cd flex/build
        # load graph
        ./bin/graph_db_loader -g ${flex_test_dir}/ldbc-sf01-long-date/audit_graph_schema.yaml \
            -d ${GITHUB_WORKSPACE}/csr-data-dir -l  ${flex_test_dir}/ldbc-sf01-long-date/audit_bulk_load.yaml

        # run validation
        ./tests/gs_tests/validator ${flex_test_dir}/sf01_validation/ \
           ${flex_test_dir}/ldbc-sf01-long-date/audit_graph_schema.yaml \
           ${flex_test_dir}/ldbc-sf01-long-date/audit_bulk_load.yaml \
           ${GITHUB_WORKSPACE}/csr-data-dir
